// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjpI7-s00KcgJhqJQJU1s9kIYfVVpbRc4',
    appId: '1:323178767740:web:811b17c145d5a27f74b0f9',
    messagingSenderId: '323178767740',
    projectId: 'ufoapp-11b58',
    authDomain: 'ufoapp-11b58.firebaseapp.com',
    storageBucket: 'ufoapp-11b58.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAulM6S-nSqflQ8OmkeGgoxohU9IQxT_Zw',
    appId: '1:323178767740:android:50012b435dc25b3674b0f9',
    messagingSenderId: '323178767740',
    projectId: 'ufoapp-11b58',
    storageBucket: 'ufoapp-11b58.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-4T6MjSi_MjWcg_Jsurisx-vOcRmbCzY',
    appId: '1:323178767740:ios:4137d08e1de525d174b0f9',
    messagingSenderId: '323178767740',
    projectId: 'ufoapp-11b58',
    storageBucket: 'ufoapp-11b58.appspot.com',
    androidClientId: '323178767740-lfkguhj8q53snagua8ca5nhfu6hqgvn6.apps.googleusercontent.com',
    iosClientId: '323178767740-k6cu290q29dnl0u88v06v127oi50kob2.apps.googleusercontent.com',
    iosBundleId: 'com.example.ufoapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-4T6MjSi_MjWcg_Jsurisx-vOcRmbCzY',
    appId: '1:323178767740:ios:6c8fbf04a8af1bf174b0f9',
    messagingSenderId: '323178767740',
    projectId: 'ufoapp-11b58',
    storageBucket: 'ufoapp-11b58.appspot.com',
    androidClientId: '323178767740-lfkguhj8q53snagua8ca5nhfu6hqgvn6.apps.googleusercontent.com',
    iosClientId: '323178767740-36hjc8srbr36o8gkbb13eh2b20leffqb.apps.googleusercontent.com',
    iosBundleId: 'com.example.ufoapp.RunnerTests',
  );
}
